// <auto-generated />
using System;
using GOASS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GOASS.Migrations
{
    [DbContext(typeof(ProduitContext))]
    partial class ProduitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GOASS.Models.Commande", b =>
                {
                    b.Property<int>("CommandeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserGuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommandeID");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("GOASS.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NomImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("GOASS.Models.ItemCommande", b =>
                {
                    b.Property<int>("ItemCommandeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommandeID")
                        .HasColumnType("int");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<double>("MontantUnitaire")
                        .HasColumnType("float");

                    b.Property<int>("ProduitID")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("ItemCommandeID");

                    b.HasIndex("CommandeID");

                    b.HasIndex("ImageID");

                    b.HasIndex("ProduitID");

                    b.ToTable("ItemCommande");
                });

            modelBuilder.Entity("GOASS.Models.ItemPanier", b =>
                {
                    b.Property<int>("ItemPanierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PanierID")
                        .HasColumnType("int");

                    b.Property<int>("ProduitID")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("ItemPanierID");

                    b.HasIndex("PanierID");

                    b.HasIndex("ProduitID");

                    b.ToTable("ItemPanier");
                });

            modelBuilder.Entity("GOASS.Models.Panier", b =>
                {
                    b.Property<int>("PanierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserGuid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PanierID");

                    b.ToTable("Panier");
                });

            modelBuilder.Entity("GOASS.Models.Produit", b =>
                {
                    b.Property<int>("ProduitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<string>("Marque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomProduit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.Property<int?>("ProduitID1")
                        .HasColumnType("int");

                    b.Property<int>("Quantité")
                        .HasColumnType("int");

                    b.Property<string>("Sport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Taille")
                        .HasColumnType("int");

                    b.HasKey("ProduitID");

                    b.HasIndex("ImageID");

                    b.HasIndex("ProduitID1");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("GOASS.Models.ItemCommande", b =>
                {
                    b.HasOne("GOASS.Models.Commande", "Commande")
                        .WithMany("Items")
                        .HasForeignKey("CommandeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GOASS.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID");

                    b.HasOne("GOASS.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Image");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GOASS.Models.ItemPanier", b =>
                {
                    b.HasOne("GOASS.Models.Panier", "Panier")
                        .WithMany("ItemPanier")
                        .HasForeignKey("PanierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GOASS.Models.Produit", "Produit")
                        .WithMany("ItemPanier")
                        .HasForeignKey("ProduitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GOASS.Models.Produit", b =>
                {
                    b.HasOne("GOASS.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID");

                    b.HasOne("GOASS.Models.Produit", null)
                        .WithMany("Produits")
                        .HasForeignKey("ProduitID1");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("GOASS.Models.Commande", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GOASS.Models.Panier", b =>
                {
                    b.Navigation("ItemPanier");
                });

            modelBuilder.Entity("GOASS.Models.Produit", b =>
                {
                    b.Navigation("ItemPanier");

                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
